keys:
  - &global age1rr03jh0pdat444rhr4rahj3hus64gdfjm3pzayn8aykyq6f0tq2qqw5qg2
  - &hosts:
    - &alpha age1xs8wq47r0z3vwm07fe0zd5jt4vzmy6zvz4s5czfp99q2svr2d5aqvjec0h
    - &beta age1fduxce42kleecefwtu28lprufs5rsuw07kp9rszgkn2kjsgmzgxs5mxrwc
    - &omega age1llsz9y0zl02d42maknvrjnf66tqz2cgq83m7hlgqpquc8vvx0phs0qmh8u
    - &gamma age1q0azy7tauvu6u2q5lyndtdhlt537etz08ahyygt7p0trdsqws3jqpnpasl
    - &theta age1zq7cczunte3dgjq54thqy7533d3y5ml04et9vr3jdfsxqctz2c9spce4ml
    - &upsilon age1l0qe4csr0rcxk2t0axywjzn0gvk82u7s2vzuur53jv80tpzg4s5smh5jdn
  - &home-manager:
    - &home-gamma age1qvddpctmj2k0hmeu428a4l952rv8pj79hwntf5qcemmr9cjf7qwqk996gg
    - &home-theta age1qu8pv5vtfujwf9cy48js8g9l69rlp9rsujr4wdyylt9qqqqlacksgu68hr
    - &home-upsilon age1uq4vutgawyrxrthjas4pzps4np9c5ky6y84c46zxe2ef0g9zje2qc2hutu
creation_rules:
  - path_regex: secrets.ya?ml$
    key_groups:
      - age:
        - *global
        - *alpha
        - *beta
        - *omega
        - *gamma
        - *theta
        - *upsilon
        - *home-gamma
        - *home-theta
        - *home-upsilon
