# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  netbird = {
    pname = "netbird";
    version = "v0.45.2";
    src = fetchFromGitHub {
      owner = "netbirdio";
      repo = "netbird";
      rev = "v0.45.2";
      fetchSubmodules = false;
      sha256 = "sha256-lvulqneKFxmZ/EQDmQbx1SzsfZxLb8tGyLFJo8z9U0w=";
    };
    vendorHash = "sha256-EVhtxYDinmid5C/3N8UGmCzWw1qIE3m0rXes4uFpcOM=";
  };
}
