# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  netbird = {
    pname = "netbird";
    version = "v0.45.1";
    src = fetchFromGitHub {
      owner = "netbirdio";
      repo = "netbird";
      rev = "v0.45.1";
      fetchSubmodules = false;
      sha256 = "sha256-55Vyhzt0WtJRq9CcH7mXw7cklAce/lvC1S+MBMDnMbo=";
    };
    vendorHash = "sha256-EVhtxYDinmid5C/3N8UGmCzWw1qIE3m0rXes4uFpcOM=";
  };
}
