# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  netbird = {
    pname = "netbird";
    version = "v0.64.1";
    src = fetchFromGitHub {
      owner = "netbirdio";
      repo = "netbird";
      rev = "v0.64.1";
      fetchSubmodules = false;
      sha256 = "sha256-fxQ6x/MN3FKRiGgb8OPjLnHCVjYnI4vBLwjDKAxrUQY=";
    };
    vendorHash = "sha256-suQPYxZo1R2Jh4N2ulOysfhRKAnVUUMzJoj+5lmhwDk=";
  };
}
