name: "build"

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
    types: [opened, reopened]

jobs:
  nixos-configurations:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # Here we specify the matrix of our hosts and their target platform architectures
      matrix:
        machine:
          - host: alpha
            platform: x86_64-linux
            large: true
          - host: beta
            platform: x86_64-linux
            large: true
          - host: omega
            platform: x86_64-linux
            large: true
          - host: epsilon
            platform: aarch64-linux
            large: false

    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        if: matrix.machine.large == true
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true

      # We only run this if we are building an aarch64-linux system
      - if: matrix.machine.platform == 'aarch64-linux'
        uses: docker/setup-qemu-action@v3

      - name: Install Nix
        if: github.event_name != 'pull_request'
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            # access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            keep-outputs = true
            extra-platforms = aarch64-linux i686-linux
            substituters = ${{ secrets.ATTIC_URL }}/system?priority=43 https://nix-community.cachix.org?priority=41 https://numtide.cachix.org?priority=42 https://cache.nixos.org/ https://hyprland.cachix.org
            trusted-public-keys = system:51hbrsnX2pmCB3z3otgdnt2aq+konejsg/bQ7Qu1W+o= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= numtide.cachix.org-1:2ps1kLBUWjxIneOy1Ik6cQjb41X0iXVXeHigGmycPPE= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc=

      - name: Install Nix
        if: github.event_name == 'pull_request'
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            # access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            keep-outputs = true
            extra-platforms = aarch64-linux i686-linux
            substituters = https://nix-community.cachix.org?priority=41 https://numtide.cachix.org?priority=42 https://cache.nixos.org/ https://hyprland.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= numtide.cachix.org-1:2ps1kLBUWjxIneOy1Ik6cQjb41X0iXVXeHigGmycPPE= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc=

      # We build each system in a separate job, targeting the configuration using matrix.machine.host
      - name: Build system
        run: nix build .#nixosConfigurations.${{ matrix.machine.host }}.config.system.build.toplevel

      # Once built, we login to Attic
      - name: Login to attic
        run: nix develop .#ci --command attic login cache ${{ secrets.ATTIC_URL }} ${{ secrets.ATTIC_TOKEN }}

      # push the built system to our `system` cache!
      - name: Push system
        run: nix develop .#ci --command attic push system result -j 2
        continue-on-error: true
